stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle build
  tags:
    - linux
    - java
    - gradle

deploy:
  stage: deploy
  script:
    - gradle publishToWebServer
  tags:
    - linux
    - java
    - gradle
  only:
    - tags